name: Test, lint & build
on:
  pull_request

jobs:
  test-lint:
    name: Test & lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ github.repository }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.repository }}-
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ github.repository }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.repository }}-
      - run: yarn install --frozen-lockfile
      - run: yarn build
